// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BinaryCrossentropy() {
  return window['go']['main']['App']['BinaryCrossentropy']();
}

export function Regression() {
  return window['go']['main']['App']['Regression']();
}
